name: common_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pip
    -  pip:
        - numpy
        - pandas
        - matplotlib
        - pillow
        - seaborn
        - scikit-learn
        - scikit-image
        - loguru
        - hydra-core
        - jupyterlab
        - jupyter
        - lightning
        - diffusers
        - neptune
        - ollama
        - litellm
        - faiss
        - albumentations
        - opencv-python
        - tensorboard
        - chromadb
        - sentence-transformers
        - rank-bm25
        - deepeval
        - tiktoken
        - langchain
        - langchain-community
        - langchain-ollama
        - langchain-nomic
        - langchain-chroma
        - nomic[local]
        - langgraph
        - datasets
        - bitsandbytes
        - docarray
        - tavily-python
        - bs4
        - langdetect
        - crawlee
        - bertopic
