name: prism_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - numpy
    - pandas
    - tqdm
    - jupyterlab
    - jupyter
    - ollama
    - litellm
    - faiss
    -   pip:
            - sentence-transformers
            - transformers
            - deepeval
            - crawlee
