name: common_env
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.12
    - pip
    - numpy
    - pandas
    - matplotlib
    - pillow
    - seaborn
    - scikit-learn
    - scikit-image
    - loguru
    - tqdm
    - hydra-core
    - jupyterlab
    - jupyter
    - h5py
    - lightning
    - diffusers
    - neptune
    - ollama
    - litellm
    - logfire
    - faiss
    -   pip:
            - albumentations
            - opencv-python
            - tensorboard
            - llama-index
            - llama-index-embeddings-ollama
            - llama-index-llms-ollama
            - chromadb
            - sentence-transformers
            - rank-bm25
            - deepeval
            - smolagents
            - gradio
            - tiktoken
            - langchain
            - langchain-community
            - langchain-ollama
            - langchain-nomic
            - langchain-chroma
            - nomic[local]
            - langgraph
            - datasets
            - bitsandbytes
            - docarray
            - tavily-python
            - bs4
            - langfuse
            - langdetect
            - crawlee
            - bertopic
